### PR TITLE
Fix edge case handling for `SCIPY/STATS/TMIN` and `SCIPY/STATS/TMAX`

### PR DESCRIPTION
**Pull request by Roulbac**
The node test failed on Windows due to improper return type handling, see https://github.com/flojoy-io/nodes/actions/runs/5650629568/job/15307323474

This PR fixes the issue by checking for the `numpy.number` type.

### CODE REVIEW

**Comment by Roulbac** [comment]
@dstrande Please only review pending passing windows tests

**Comment by dstrande** [comment]
Other nodes have the same union type checking and should probably have this fix applied.

**Comment by Roulbac** [comment]
Looks fine for this PR, I wonder however if we need a convenience functions as part of `flojoy` itself to do all of these recurring data type transformations. Seems like for 1 fix we need to do 50 changes in 50 different places atm

**Comment by dstrande** [comment]
There is a script right now that writes all 50 nodes and their tests. modole_scraper.py in the python repo. At some point it might be a good idea to automate it more. I have many improvements planned for the numpy/scipy autogen. I'm just taking a break from them right now.

**Pull request merged**
