### PR TITLE
Camera + Detect edits

### PR DESCRIPTION
**Pull request by dstrande**
### Description

Addition of resolution selection to CAMERA. 
Move YOLOV3 check/download to OBJECT_DETECTION node from bash script.

- [x] I've included a concise description of what each node does

### Styleguide

- [x] My node adheres to the [styleguide](https://github.com/flojoy-io/nodes/blob/main/node_styleguide.md) for Flojoy nodes

### Docs

- [x] I've submitted a PR for a documentation page for the new node(s) that contains usage examples (see docs.flojoy.io)

### CODE REVIEW

**Comment by smahmed776** [comment]
@dstrande Could you please update the docstring to align with Styleguide as you modified these nodes? Everything else LGTM

**Comment by dstrande** [comment]
@smahmed776 let me know how it looks now then I'll deal with the nodes conflicts.

**Review by smahmed776 — APPROVED** [review]
LGTM

**Comment by dstrande** [comment]
@smahmed776 good to merge

**Pull request merged**
