### PR TITLE
Replace all occurrences of v with dc in params of functions

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
Hey @jackparmer 
This PR is for issue #29. Please let me know in case of any feedback.

### CODE REVIEW

**Comment by ujwalkumar1995** [comment]
Sure @jackparmer 
Will make this change

**Comment by ujwalkumar1995** [comment]
Hey @jackparmer 
Have made the suggested changes, please review.

**Comment by smahmed776** [comment]
@ujwalkumar1995 Can you please make sure that all checks in CI are passed?

**Comment by ujwalkumar1995** [comment]
Hey @smahmed776 
I have fixed the CI bug. It should pass now. Could you please check?

**Comment by jackparmer** [comment]
Thanks @ujwalkumar1995 !

I resolved some merge conflicts and now it looks like `black` needs to be run again - do you mind looking at this?

Also just curious -how did you come across this project?

**Comment by ujwalkumar1995** [comment]
Hey @jackparmer 
I have fixed the warnings from black.
Regarding how I did find this project. Nothing special. Was just looking for some projects to contribute on and found this issue listed.

**Comment by ujwalkumar1995** [comment]
Hey @jackparmer 
Could you review this PR and let me know in case of any changes that I need to make?

**Comment by itsjoeoui** [comment]
Hey, @ujwalkumar1995 !

Thanks a lot for your contribution! We appreciate it very much!

This is my bad, I did not see your PR, and I asked a teammate to address this issue. I just saw this after I merged my teammate's PR. I am very sorry about this 🥲.

I will close this for now. Again, I apologize for my mistake :(

Best,
Joey

(If you still feel like contributing, I promise I will pay attention next time! I created another first good issue in the issue tab if you are still interested! Thanks brother 🙏)

**Pull request closed without merging**
